# Generated by Django 4.1.7 on 2023-04-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2023-04-07'),
            preserve_default=False,
        ),
    ]
