# Generated by Django 4.1.7 on 2023-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='foodId',
            field=models.CharField(default='d5g', max_length=255),
            preserve_default=False,
        ),
    ]
