# Generated by Django 4.1.7 on 2023-03-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='dish',
        ),
        migrations.AddField(
            model_name='meal',
            name='dish',
            field=models.ManyToManyField(default='None', to='dishes.dish'),
        ),
    ]
